version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/technocorp/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
  sonarqube:
    image: library/sonarqube:8.6-community
    ports:
      - "9000:9000"